-- Add 12 Content team members (name, EMP ID, company email). Roster gate for SSO
-- + task assignment. dept/sub/manager left null — set them via Admin > Employees
-- (email is editable there). Re-runnable (upsert by id).
insert into employees (id, email, name, initials, manager_id, dept, sub, role_level, title, is_cross_dept, data) values
  ('NW0001771','meesala.chanakya@nxtwave.co.in','Chanakya Meesala','CM',null,null,null,'L1','L1 · Content',false,'{"id":"NW0001771","name":"Chanakya Meesala","initials":"CM","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0006025','yerramilli.phaniyeshwanth@nxtwave.co.in','Yerramilli Phani Yeshwanth','YP',null,null,null,'L1','L1 · Content',false,'{"id":"NW0006025","name":"Yerramilli Phani Yeshwanth","initials":"YP","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0005795','nurubasha.janibasha@nxtwave.co.in','Nurubasha Jani Basha','NJ',null,null,null,'L1','L1 · Content',false,'{"id":"NW0005795","name":"Nurubasha Jani Basha","initials":"NJ","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0003056','khushi.jain@nxtwave.co.in','Khushi Jain','KJ',null,null,null,'L1','L1 · Content',false,'{"id":"NW0003056","name":"Khushi Jain","initials":"KJ","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0003057','vipparthi.angel@nxtwave.co.in','Vipparthi Angel','VA',null,null,null,'L1','L1 · Content',false,'{"id":"NW0003057","name":"Vipparthi Angel","initials":"VA","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0003857','jeevansravanth.parisa@nxtwave.co.in','Jeevan Sravanth Parisa','JS',null,null,null,'L1','L1 · Content',false,'{"id":"NW0003857","name":"Jeevan Sravanth Parisa","initials":"JS","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0004570','priya.khairate@nxtwave.co.in','Priya Mallikarjun Khairate','PK',null,null,null,'L1','L1 · Content',false,'{"id":"NW0004570","name":"Priya Mallikarjun Khairate","initials":"PK","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0006123','prashantkumar.jha@nxtwave.co.in','Prashant Kumar Jha','PJ',null,null,null,'L1','L1 · Content',false,'{"id":"NW0006123","name":"Prashant Kumar Jha","initials":"PJ","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0006496','chittharu.nagapravallika@nxtwave.co.in','Chittharu Nagapravallika','CN',null,null,null,'L1','L1 · Content',false,'{"id":"NW0006496","name":"Chittharu Nagapravallika","initials":"CN","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW1006940','rishuraj.singh@nxtwave.co.in','Rishu Raj Singh','RS',null,null,null,'L1','L1 · Content',false,'{"id":"NW1006940","name":"Rishu Raj Singh","initials":"RS","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW1006983','dasari.pallavi@nxtwave.co.in','Dasari Pallavi','DP',null,null,null,'L1','L1 · Content',false,'{"id":"NW1006983","name":"Dasari Pallavi","initials":"DP","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb),
  ('NW0002531','soumya.esampally@nxtwave.co.in','Esampally Soumya','ES',null,null,null,'L1','L1 · Content',false,'{"id":"NW0002531","name":"Esampally Soumya","initials":"ES","role":"L1","level":"L1","dept":null,"sub":null,"title":"L1 · Content","managerId":null}'::jsonb)
on conflict (id) do update set
  email = excluded.email, name = excluded.name, initials = excluded.initials,
  role_level = excluded.role_level, title = excluded.title, data = excluded.data;
