-- Upsert the Gen AI team goals + deliverables into the goals table.
insert into goals (id, dept, sub, data) values
  ('goal-ga-1', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-1","sub":"Content — GenAI","dept":"d-fsgci","title":"IDE repairs & improvements","products":[],"deliverables":[{"id":"goal-ga-1-d1","text":"n8n IDE issue resolutions","assignees":[]},{"id":"goal-ga-1-d2","text":"Reduce IDE loading/opening time (~50s)","assignees":[]},{"id":"goal-ga-1-d3","text":"Reduce code submission time (under 1 minute)","assignees":[]},{"id":"goal-ga-1-d4","text":"IDE observability dashboard","assignees":[]},{"id":"goal-ga-1-d5","text":"Automate workflow testing with a script","assignees":[]},{"id":"goal-ga-1-d6","text":"Enhance n8n IDE exam support in LP/Topin","assignees":[]},{"id":"goal-ga-1-d7","text":"Simplify n8n submission process (8 steps + two-tab switching → fewer steps)","assignees":[]},{"id":"goal-ga-1-d8","text":"LP support for HTML-based Interactive Tutorial Builder","assignees":[]}]}'::jsonb),
  ('goal-ga-2', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-2","sub":"Content — GenAI","dept":"d-fsgci","title":"Practical Software Engineering Content Delivery","products":[],"deliverables":[{"id":"goal-ga-2-d1","text":"Fullstack AI IDE support in LP (learning, practice, exam)","assignees":[]},{"id":"goal-ga-2-d2","text":"Coding Question Generator - L3","assignees":[]},{"id":"goal-ga-2-d3","text":"Testcase-based evaluation for n8n (deterministic; replaces LLM eval that gives random scores)","assignees":[]},{"id":"goal-ga-2-d4","text":"13 session learning content","assignees":[]}]}'::jsonb),
  ('goal-ga-3', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-3","sub":"Content — GenAI","dept":"d-fsgci","title":"Introduction to Generative AI - Revamp","products":[],"deliverables":[{"id":"goal-ga-3-d1","text":"22 session learning content (spill-overs, content issues, etc.)","assignees":[]},{"id":"goal-ga-3-d2","text":"Convert RMs to Tutorials and add academic exam questions","assignees":[]},{"id":"goal-ga-3-d3","text":"Add nxtmock units","assignees":[]}]}'::jsonb),
  ('goal-ga-4', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-4","sub":"Content — GenAI","dept":"d-fsgci","title":"Gen AI Role-specific awareness Sessions - Induction","products":[],"deliverables":[{"id":"goal-ga-4-d1","text":"2 session learning content","assignees":[]}]}'::jsonb),
  ('goal-ga-5', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-5","sub":"Content — GenAI","dept":"d-fsgci","title":"AI for Finance Content Delivery","products":[],"deliverables":[{"id":"goal-ga-5-d1","text":"17 session learning content","assignees":[]}]}'::jsonb),
  ('goal-ga-6', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-6","sub":"Content — GenAI","dept":"d-fsgci","title":"Content Quality Issues & Feedback Resolution","products":[],"deliverables":[{"id":"goal-ga-6-d1","text":"Resolve all existing content feedback & quality issues (Zoho and other channels)","assignees":[]},{"id":"goal-ga-6-d2","text":"Resolve newer issues arising in July","assignees":[]}]}'::jsonb),
  ('goal-ga-7', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-7","sub":"Content — GenAI","dept":"d-fsgci","title":"Observability Systems","products":[],"deliverables":[{"id":"goal-ga-7-d1","text":"Session scheduling and delivery observability systems","assignees":[]}]}'::jsonb),
  ('goal-ga-8', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-8","sub":"Content — GenAI","dept":"d-fsgci","title":"Team Capacity Building","products":[],"deliverables":[{"id":"goal-ga-8-d1","text":"Hiring SDI - Fullstack AI","assignees":[]}]}'::jsonb),
  ('goal-ga-9', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-9","sub":"Content — GenAI","dept":"d-fsgci","title":"Stack Curriculum Redesign based on market intelligence","products":[],"deliverables":[]}'::jsonb),
  ('goal-ga-10', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-10","sub":"Content — GenAI","dept":"d-fsgci","title":"Objective Content Creator - L4","products":[],"deliverables":[]}'::jsonb),
  ('goal-ga-11', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-11","sub":"Content — GenAI","dept":"d-fsgci","title":"Interactive Tutorial Builder - L3","products":[],"deliverables":[]}'::jsonb),
  ('goal-ga-12', 'd-fsgci', 'Content — GenAI', '{"id":"goal-ga-12","sub":"Content — GenAI","dept":"d-fsgci","title":"NxtMock Question Mapper","products":[],"deliverables":[]}'::jsonb)
on conflict (id) do update set dept=excluded.dept, sub=excluded.sub, data=excluded.data;
